name: CI/CD Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx codeceptjs run --steps

      - name: Install dependencies
        run: npm install

      - name: Run CodeceptJS Tests
        run: npx codeceptjs run --headless
